### ISSUE TITLE
How to go from ITK to numpy?

### ISSUE THREAD

**Issue by vianamp** [fbudin69500/ConvertITKDatatoNumPyArrayBlogPost#2]
Hi. Thanks for the example.

Would you know how to to the inverse path? From ITK image to a numpy array?

Thanks,

**Comment by fbudin69500** [comment]
The way to go from NumPy to ITK is to use the function `itk.GetImageFromArray(arr)` or `itk.GetImageViewFromArray(arr)`.  You can refer to [this guide](https://itkpythonpackage.readthedocs.io/en/latest/Quick_start_guide.html).
